### ISSUE TITLE
群聊中的消息显示（不支持的消息：undefined）

### ISSUE THREAD

**Issue by LiangYin233** [Stapxs/QQ-Web-Lite#1]
我当前正在使用 go-cqhttp。
在群聊消息中，所有消息都被显示 不支持的消息：undefined
Like this
![图片](https://user-images.githubusercontent.com/39800913/162216409-e4083171-d236-43cf-88fc-ebf7cee05ead.png)
但是群消息预览的显示是正常的。
![图片](https://user-images.githubusercontent.com/39800913/162216542-0a87cc7b-54d2-4c79-8e5e-c4fac04f3985.png)
请问这是尚未完善还是出现了问题？
感谢

**Comment by Stapxs** [comment]
我依照 oicq-http （v1 版本） 的消息返回格式进行编写，所以只支持 oicq ，不保证其他 QQ Bot 能正常运作。
关于 oicq 可以看这 https://github.com/takayama-lily/oicq/tree/master/http-api

**Comment by Stapxs** [comment]
待我晚点看下 go-cqhttp（挠头），因为 oicq-http v1 还是 OneBot v11 的版本，指不定 v12 改了啥（捂脸）

**Comment by LiangYin233** [comment]
并且似乎 get_chat_history 是一个 OICQ 专有的 API？我看了下 Mirai/go-cqhttp 都无法找到这个API。

**Comment by LiangYin233** [comment]
还有你编辑的那一段一看log就是老furry了（（

**Comment by LiangYin233** [comment]
最开始我以为OICQ是指QQ一开始的名字。。。不知道是个机器人框架ww

**Comment by Stapxs** [comment]
> 
现在 QQBot Http 遵守的协议一般是 OneBot ：https://github.com/botuniverse/onebot-11/ ，这样可以让大家都尽量兼容同一套方法。

OneBot 11 的功能对 Bot 来说够用了，但是对一个完整客户端还是有点不足，oicq 还加了不少功能 ：https://github.com/takayama-lily/oicq/blob/4aef20108d428e4f6c02a3c3e38a8ab6d3768494/http-api/README.md?plain=1#L84

我看了下 OneBot 12 的草案协议还是没获取历史消息之类的接口规范 …… 估计还是得只支持 oicq 了（小声）

**Comment by Stapxs** [comment]
> 还有你编辑的那一段一看log就是老furry了（（

草，这也能看出来
![O%{EBQ 6Y$ `Y~{VX}D8J5U](https://user-images.githubusercontent.com/42486439/162364583-1c2c560e-7994-40b5-85b5-d2b537d1def6.jpg)

**Comment by LiangYin233** [comment]
OK,thx

**Comment by LiangYin233** [comment]
> > 还有你编辑的那一段一看log就是老furry了（（
> 
> 草，这也能看出来 ![O%{EBQ 6Y$ `Y~{VX}D8J5U](https://user-images.githubusercontent.com/42486439/162364583-1c2c560e-7994-40b5-85b5-d2b537d1def6.jpg)

23333333，头像便知(bushi

**Comment by LiangYin233** [comment]
草，bakaxl,作者成分复杂(*tt万岁

**Comment by ctaoist** [comment]
https://github.com/Mrs4s/go-cqhttp/pull/1742 go-cqhttp 已经提交了这个接口的 PR

**Comment by ctaoist** [comment]
刚想 pr 一个支持go-cqhttp的网页版，已经写完了，结果发现有个2.0分支！！！！

**Comment by Stapxs** [comment]
> 刚想 pr 一个支持go-cqhttp的网页版，已经写完了，结果发现有个2.0分支！！！！

2.0 还在暴风摸鱼（
2.0 将会使用自己魔改的 oicq http bot 所以可能对其他 bot 的兼容会更困难 emmm
1.0 也还是会继续维护的不过不会加新的功能了
