### ISSUE TITLE
无法加载个人聊天，只能加载群聊

### ISSUE THREAD

**Issue by zhou41698** [Stapxs/QQ-Web-Lite#21]
群聊发消息没问题，向个人发消息时会提示无法加载，但是对方的确收到了消息（疑惑）。OICQ的错误代码是`[2022-05-12T10:17:33.227] [ERROR] [Android:QQ号码] - Invoke failed, because -> msg not exists
` google后找不到，只能求助大大了。望解答~~💕💕

**Comment by Stapxs** [comment]
获取发送消息失败会再重试最多五次也全部失败？

**Comment by zhou41698** [comment]
上面显示的是失败，我这边无法显示消息。但是对方却收到了消息~😂

**Comment by Stapxs** [comment]
emmm
不太清楚，怀疑是风控 ……
QQ 对私聊消息的管理比群聊严格
比如现在 oicq 只能获取最多一天前的私聊消息之类的 ……

我前几天也莫名其妙获取不到私聊消息，估计也差不多，这个我解决不了（小声

**Comment by zhou41698** [comment]
那好吧，谢谢。（已经把官方qq下下来了
