### ISSUE TITLE
支持表情发送？

### ISSUE THREAD

**Issue by wuxian425** [Stapxs/QQ-Web-Lite#22]
如题，不支持表情发送有点蓝瘦（悲

**Comment by Stapxs** [comment]
你暂时可以用 CQ 码发送表情（
我没做表情选择框 ……

[CQ:face,id=x]

id 是在官方表情选择里的顺序，第一个微笑就是 0
晚点我会写表情选择框（xxxx

![image](https://user-images.githubusercontent.com/42486439/169688953-698c0527-dfe2-4045-b979-e464951bd8ab.png)

**Comment by Stapxs** [comment]
emmm 以及如果是收藏表情
那个没办法，QQ 的 API 全都不允许跨域 ……
网页访问会被拦死

**Comment by wuxian425** [comment]
好诶！

**Comment by wuxian425** [comment]
对了，QQ-Face表情缺失颇多有考虑补充吗？

**Comment by Stapxs** [comment]
> 对了，QQ-Face表情缺失颇多有考虑补充吗？

事实上表情的支持度取决于 QQ Bot 支持多少，由于目前还没支持 oicq 2.0（有很多 API 修改我懒得改了（小声））
所以只能依照 oicq 1.0 支持的量了

以及 oicq 2.0 作者还没写 http 版本 …… 暂时也没法升上去（

**Comment by wuxian425** [comment]
指qq-face这个资料夹，狗头似乎不存在但是是收的到的

**Comment by Stapxs** [comment]
> 指qq-face这个资料夹，狗头似乎不存在但是是收的到的

这玩意是我从 go-cqhttp 掏过来的（x
(https://github.com/kyubotics/coolq-http-api/wiki/%E8%A1%A8%E6%83%85-CQ-%E7%A0%81-ID-%E8%A1%A8)
晚点我去找找新的 emmm

**Comment by Stapxs** [comment]
我拆开了 QQ 安卓版的安装包尝试找一些表情出来 ……
但是我只找到了缺失的部分没有 / 开头的表情

![image](https://user-images.githubusercontent.com/42486439/169701310-2d3ee0a8-e4d4-4407-8a73-e1cf9badd4de.png)
![image](https://user-images.githubusercontent.com/42486439/169701318-f515690e-89c6-45bc-a82a-81ad68674c41.png)

找不到剩余的其他表情文件 …… 暂时不知道该怎么办 ……

**Comment by Stapxs** [comment]
#23
