### ISSUE TITLE
表情选择框（更多功能扩展框）

### ISSUE THREAD

**Issue by wuxian425** [Stapxs/QQ-Web-Lite#25]
rt，顺便锤更昨天那个表情输入（bushi

**Comment by Stapxs** [comment]
群聊消息本来就不作为新消息提醒（
毕竟群实在是太多了，全提醒得烦死
等几天等几天我最近好忙的（大声

**Comment by Stapxs** [comment]
如果你真的要让群聊消息也按照私聊提醒的话我可以加个选项（？

**Comment by wuxian425** [comment]
> 如果你真的要让群聊消息也按照私聊提醒的话我可以加个选项（？

感觉不戳

**Comment by Stapxs** [comment]
我关了，我又开了，欸我还要改你标题（xxx

**Comment by Stapxs** [comment]
https://github.com/Stapxs/Stapxs-QQ-Lite/commit/bb87a5f649133e3dae7dcd4024050500328c1112

**Comment by wuxian425** [comment]
好耶
