### ISSUE TITLE
[错误] 合并消息详情位置问题

### ISSUE THREAD

**Issue by IJustWantANamePlease** [Stapxs/QQ-Web-Lite#27]
**描述错误**
在连接后SQL窗口会占满屏幕，但合并消息详情的界面仍在以前的位置

**复现流程**
-打开并连接OICQ（或者别的什么反正这不重要）
-找到一条合并消息
-点开

**截图**
![IMG_20220524_142420](https://user-images.githubusercontent.com/69347951/169962984-3f73c4a5-9af7-492a-af91-ffecaf80384b.png)

**版本信息**
- Stapxs QQ Lite 版本：v1.292
- 浏览器：火狐
- 浏览器版本：100.0.2

**更多**
在别的issue那看到你说自己很忙了，但我还是想发（逃）

**Comment by Stapxs** [comment]
oh，是我改了大布局导致的（
晚点修（恼
