### ISSUE TITLE
[ BUG 提醒 ] 关于 Chrome 102 #1329248 错误带来的问题

### ISSUE THREAD

**Issue by Stapxs** [Stapxs/QQ-Web-Lite#30]
如果你正在使用 Chrome 102 的最新版本并出现了缓存外的头像无法被加载的问题
![image](https://user-images.githubusercontent.com/42486439/172161989-5c929d19-3ad9-42a1-b58d-03636f7f0969.png)
[ 就像这样 ]

那么，这并不是 Stapxs QQ Lite 的错误，这是来自于 Chromium 新支持 PNA 规范的 BUG。该 BUG 会导致资源加载失败。
请参考这个 BUG 条目：
https://bugs.chromium.org/p/chromium/issues/detail?id=1329248

暂且需要等待 Chrome 修复，如果你已经升级到了 Chrome 102 版本，那么你可以考虑用 Firefox 临时替代。

**Comment by Stapxs** [comment]
这个 BUG 甚至导致我连 GitHub 的 CSS 都加载不出来

![image](https://user-images.githubusercontent.com/42486439/172164368-8571638c-1111-4455-8350-e5e476d8d4b6.png)

**Comment by cnrkuo** [comment]
建議都用 Firefox 做日常使用（doge
