### ISSUE TITLE
時間錯誤

### ISSUE THREAD

**Issue by wuxian425** [Stapxs/QQ-Web-Lite#31]
最新版本Stapxs-QQ-Lite 顯示之時間多了一個小時 XD

**Comment by Stapxs** [comment]
SS 内心：js 获取的小时是 0 开始的不应该要加一么
（无响应.png * 1min）
SS：哦小时本来就是 0 开始的（恼

**Comment by wuxian425** [comment]
草哈哈哈哈哈哈哈哈
