### ISSUE TITLE
[弱鸡求助：连接不上服务器]

### ISSUE THREAD

**Issue by timeForgiven** [Stapxs/QQ-Web-Lite#32]
**描述错误**
小白弱鸡求助，希望大佬指点。我在本地用localhost能够成功使用Stapxs QQ Lite。然而将oicq部署到云服务器上，Stapxs QQ Lite却连接不上，错误代码1006。服务器操作系统centos，在服务器端能正常运行oicq并用send <target> <message>成功测试。更换过不同端口，也给端口安全权限，都不行。希望大佬指点，弱鸡给出服务器的账户名和密码，成功之后请大佬喝奶茶，跪谢大佬

**复现流程**
同上

**截图**
服务器
![image](https://user-images.githubusercontent.com/106787047/177238210-a807c15e-9de2-4c80-9f74-e159b914ced0.png)
Stapxs QQ Lite
![image](https://user-images.githubusercontent.com/106787047/177238302-c0661164-9044-4315-8958-0484c84c236d.png)

**版本信息**
我需要知道 Stapxs QQ Lite 的版本和浏览器的信息，你可以在设置的最底下看见版本信息。
- Stapxs QQ Lite 版本：v1.2943
- 浏览器：Edge
- 浏览器版本：103.0.1264.44

**其他联系方式**
QQ:xxxxxxxxxx

**Comment by Stapxs** [comment]
1006 大半是根本就没连上 hummm
建议先尝试在目标机器上用 telnet 检查下服务器能连上并且端口真的能用(

![image](https://user-images.githubusercontent.com/42486439/177298155-d1f10ad3-9397-42e2-8baf-9a529d780576.png)

**Comment by timeForgiven** [comment]
> 1006 大半是根本就没连上 hummm 建议先尝试在目标机器上用 telnet 检查下服务器能连上并且端口真的能用(
> 
> ![image](https://user-images.githubusercontent.com/42486439/177298155-d1f10ad3-9397-42e2-8baf-9a529d780576.png)

我在服务器端用了telnet测试，这个端口应该是没问题的
![image](https://user-images.githubusercontent.com/106787047/177312434-909b3f62-23b8-41a6-8e67-a430e3db6769.png)
我在本地windows上用telnet <公网IP> <端口号>进行测试，也是能连接上的
😢不知道问题出在哪里 @Stapxs

**Comment by Stapxs** [comment]
> > 1006 大半是根本就没连上 hummm 建议先尝试在目标机器上用 telnet 检查下服务器能连上并且端口真的能用(
> > ![image](https://user-images.githubusercontent.com/42486439/177298155-d1f10ad3-9397-42e2-8baf-9a529d780576.png)
> 
> 我在服务器端用了telnet测试，这个端口应该是没问题的 ![image](https://user-images.githubusercontent.com/106787047/177312434-909b3f62-23b8-41a6-8e67-a430e3db6769.png) 我在本地windows上用telnet <公网IP> <端口号>进行测试，也是能连接上的 cry不知道问题出在哪里 @Stapxs

我指的是要连接服务器的设备 telnet 连不连得上服务器
我用 localhost 演示可能误导了因为我服务器不能暴露 IP(

**Comment by timeForgiven** [comment]
> > > 1006 大半是根本就没连上 hummm 建议先尝试在目标机器上用 telnet 检查下服务器能连上并且端口真的能用(
> > > ![image](https://user-images.githubusercontent.com/42486439/177298155-d1f10ad3-9397-42e2-8baf-9a529d780576.png)
> > 
> > 
> > 我在服务器端用了telnet测试，这个端口应该是没问题的 ![image](https://user-images.githubusercontent.com/106787047/177312434-909b3f62-23b8-41a6-8e67-a430e3db6769.png) 我在本地windows上用telnet <公网IP> <端口号>进行测试，也是能连接上的 cry不知道问题出在哪里 @Stapxs
> 
> 我指的是要连接设备 telnet 连不连得上服务器 我用 localhost 演示可能误导了因为我服务器不能暴露 IP(

我明白了，但是我要连接设备就是本地的windows,能连接上服务器的 😢

**Comment by Stapxs** [comment]
> > > > 1006 大半是根本就没连上 hummm 建议先尝试在目标机器上用 telnet 检查下服务器能连上并且端口真的能用(
> > > > ![image](https://user-images.githubusercontent.com/42486439/177298155-d1f10ad3-9397-42e2-8baf-9a529d780576.png)
> > > 
> > > 
> > > 我在服务器端用了telnet测试，这个端口应该是没问题的 ![image](https://user-images.githubusercontent.com/106787047/177312434-909b3f62-23b8-41a6-8e67-a430e3db6769.png) 我在本地windows上用telnet <公网IP> <端口号>进行测试，也是能连接上的 cry不知道问题出在哪里 @Stapxs
> > 
> > 
> > 我指的是要连接设备 telnet 连不连得上服务器 我用 localhost 演示可能误导了因为我服务器不能暴露 IP(
> 
> 我明白了，但是我要连接设备就是本地的windows,能连接上服务器的 cry

诶 …… 你填的啥（超小声

**Comment by timeForgiven** [comment]
> > > > > 1006 大半是根本就没连上 hummm 建议先尝试在目标机器上用 telnet 检查下服务器能连上并且端口真的能用(
> > > > > ![image](https://user-images.githubusercontent.com/42486439/177298155-d1f10ad3-9397-42e2-8baf-9a529d780576.png)
> > > > 
> > > > 
> > > > 我在服务器端用了telnet测试，这个端口应该是没问题的 ![image](https://user-images.githubusercontent.com/106787047/177312434-909b3f62-23b8-41a6-8e67-a430e3db6769.png) 我在本地windows上用telnet <公网IP> <端口号>进行测试，也是能连接上的 cry不知道问题出在哪里 @Stapxs
> > > 
> > > 
> > > 我指的是要连接设备 telnet 连不连得上服务器 我用 localhost 演示可能误导了因为我服务器不能暴露 IP(
> > 
> > 
> > 我明白了，但是我要连接设备就是本地的windows,能连接上服务器的 cry
> 
> 诶 …… 你填的啥（超小声

![image](https://user-images.githubusercontent.com/106787047/177314338-b7a16d7f-2df2-4a02-b1ac-ff50959331a0.png)

**Comment by timeForgiven** [comment]
> > > > > 1006 大半是根本就没连上 hummm 建议先尝试在目标机器上用 telnet 检查下服务器能连上并且端口真的能用(
> > > > > ![image](https://user-images.githubusercontent.com/42486439/177298155-d1f10ad3-9397-42e2-8baf-9a529d780576.png)
> > > > 
> > > > 
> > > > 我在服务器端用了telnet测试，这个端口应该是没问题的 ![image](https://user-images.githubusercontent.com/106787047/177312434-909b3f62-23b8-41a6-8e67-a430e3db6769.png) 我在本地windows上用telnet <公网IP> <端口号>进行测试，也是能连接上的 cry不知道问题出在哪里 @Stapxs
> > > 
> > > 
> > > 我指的是要连接设备 telnet 连不连得上服务器 我用 localhost 演示可能误导了因为我服务器不能暴露 IP(
> > 
> > 
> > 我明白了，但是我要连接设备就是本地的windows,能连接上服务器的 cry
> 
> 诶 …… 你填的啥（超小声
![image](https://user-images.githubusercontent.com/106787047/177314477-f2bad941-5430-40a4-9392-e0c8f609abc4.png)

Windows上连接以后是黑框，我查了一下是正常的

**Comment by Stapxs** [comment]
> > > > > > 1006 大半是根本就没连上 hummm 建议先尝试在目标机器上用 telnet 检查下服务器能连上并且端口真的能用(
> > > > > > ![image](https://user-images.githubusercontent.com/42486439/177298155-d1f10ad3-9397-42e2-8baf-9a529d780576.png)
> > > > > 
> > > > > 
> > > > > 我在服务器端用了telnet测试，这个端口应该是没问题的 ![image](https://user-images.githubusercontent.com/106787047/177312434-909b3f62-23b8-41a6-8e67-a430e3db6769.png) 我在本地windows上用telnet <公网IP> <端口号>进行测试，也是能连接上的 cry不知道问题出在哪里 @Stapxs
> > > > 
> > > > 
> > > > 我指的是要连接设备 telnet 连不连得上服务器 我用 localhost 演示可能误导了因为我服务器不能暴露 IP(
> > > 
> > > 
> > > 我明白了，但是我要连接设备就是本地的windows,能连接上服务器的 cry
> > 
> > 
> > 诶 …… 你填的啥（超小声
> > ![image](https://user-images.githubusercontent.com/106787047/177314477-f2bad941-5430-40a4-9392-e0c8f609abc4.png)
> 
> Windows上连接以后是黑框，我查了一下是正常的

哦我大概知道是为什么了 ……
因为浏览器不把非 localhost 的地址认为是安全的，但是 github pages 的页面是 https 的，这意味着连没有 SSL 的 ws 服务的时候被浏览器直接掐了 ……

你先试试克隆下仓库直接开 index.html 连不连得上，连得上那就是这个原因了（

**Comment by timeForgiven** [comment]
> > > > > > > 1006 大半是根本就没连上 hummm 建议先尝试在目标机器上用 telnet 检查下服务器能连上并且端口真的能用(
> > > > > > > ![image](https://user-images.githubusercontent.com/42486439/177298155-d1f10ad3-9397-42e2-8baf-9a529d780576.png)
> > > > > > 
> > > > > > 
> > > > > > 我在服务器端用了telnet测试，这个端口应该是没问题的 ![image](https://user-images.githubusercontent.com/106787047/177312434-909b3f62-23b8-41a6-8e67-a430e3db6769.png) 我在本地windows上用telnet <公网IP> <端口号>进行测试，也是能连接上的 cry不知道问题出在哪里 @Stapxs
> > > > > 
> > > > > 
> > > > > 我指的是要连接设备 telnet 连不连得上服务器 我用 localhost 演示可能误导了因为我服务器不能暴露 IP(
> > > > 
> > > > 
> > > > 我明白了，但是我要连接设备就是本地的windows,能连接上服务器的 cry
> > > 
> > > 
> > > 诶 …… 你填的啥（超小声
> > > ![image](https://user-images.githubusercontent.com/106787047/177314477-f2bad941-5430-40a4-9392-e0c8f609abc4.png)
> > 
> > 
> > Windows上连接以后是黑框，我查了一下是正常的
> 
> 哦我大概知道是为什么了 …… 因为浏览器不把非 localhost 的地址认为是安全的，但是 github pages 的页面是 https 的，这意味着连没有 SSL 的 ws 服务的时候被浏览器直接掐了 ……
> 
> 你先试试克隆下仓库直接开 index.html 连不连得上，连得上那就是这个原因了（

好的，我试试

**Comment by timeForgiven** [comment]
> > > > > > > 1006 大半是根本就没连上 hummm 建议先尝试在目标机器上用 telnet 检查下服务器能连上并且端口真的能用(
> > > > > > > ![image](https://user-images.githubusercontent.com/42486439/177298155-d1f10ad3-9397-42e2-8baf-9a529d780576.png)
> > > > > > 
> > > > > > 
> > > > > > 我在服务器端用了telnet测试，这个端口应该是没问题的 ![image](https://user-images.githubusercontent.com/106787047/177312434-909b3f62-23b8-41a6-8e67-a430e3db6769.png) 我在本地windows上用telnet <公网IP> <端口号>进行测试，也是能连接上的 cry不知道问题出在哪里 @Stapxs
> > > > > 
> > > > > 
> > > > > 我指的是要连接设备 telnet 连不连得上服务器 我用 localhost 演示可能误导了因为我服务器不能暴露 IP(
> > > > 
> > > > 
> > > > 我明白了，但是我要连接设备就是本地的windows,能连接上服务器的 cry
> > > 
> > > 
> > > 诶 …… 你填的啥（超小声
> > > ![image](https://user-images.githubusercontent.com/106787047/177314477-f2bad941-5430-40a4-9392-e0c8f609abc4.png)
> > 
> > 
> > Windows上连接以后是黑框，我查了一下是正常的
> 
> 哦我大概知道是为什么了 …… 因为浏览器不把非 localhost 的地址认为是安全的，但是 github pages 的页面是 https 的，这意味着连没有 SSL 的 ws 服务的时候被浏览器直接掐了 ……
> 
> 你先试试克隆下仓库直接开 index.html 连不连得上，连得上那就是这个原因了（

牛啊，果然是这个原因👍

**Comment by timeForgiven** [comment]
> > > > > > > 1006 大半是根本就没连上 hummm 建议先尝试在目标机器上用 telnet 检查下服务器能连上并且端口真的能用(
> > > > > > > ![image](https://user-images.githubusercontent.com/42486439/177298155-d1f10ad3-9397-42e2-8baf-9a529d780576.png)
> > > > > > 
> > > > > > 
> > > > > > 我在服务器端用了telnet测试，这个端口应该是没问题的 ![image](https://user-images.githubusercontent.com/106787047/177312434-909b3f62-23b8-41a6-8e67-a430e3db6769.png) 我在本地windows上用telnet <公网IP> <端口号>进行测试，也是能连接上的 cry不知道问题出在哪里 @Stapxs
> > > > > 
> > > > > 
> > > > > 我指的是要连接设备 telnet 连不连得上服务器 我用 localhost 演示可能误导了因为我服务器不能暴露 IP(
> > > > 
> > > > 
> > > > 我明白了，但是我要连接设备就是本地的windows,能连接上服务器的 cry
> > > 
> > > 
> > > 诶 …… 你填的啥（超小声
> > > ![image](https://user-images.githubusercontent.com/106787047/177314477-f2bad941-5430-40a4-9392-e0c8f609abc4.png)
> > 
> > 
> > Windows上连接以后是黑框，我查了一下是正常的
> 
> 哦我大概知道是为什么了 …… 因为浏览器不把非 localhost 的地址认为是安全的，但是 github pages 的页面是 https 的，这意味着连没有 SSL 的 ws 服务的时候被浏览器直接掐了 ……
> 
> 你先试试克隆下仓库直接开 index.html 连不连得上，连得上那就是这个原因了（

克隆下来就没问题了

**Comment by Stapxs** [comment]
那这样就要么给 ws 反代个 wss 服务出来，要么在本地挂个 http 服务挂页面 emmm
不太建议直接用文件开我在 readme 里写了坏处（

**Comment by timeForgiven** [comment]
> 那这样就要么给 ws 反代个 wss 服务出来，要么在本地挂个 http 服务挂页面 emmm 不太建议直接用文件开我在 readme 里写了坏处（

如何用 ws 反代个 wss 服务呢？我对这方面不太熟，大佬能再指点一下吗？🤔

**Comment by Stapxs** [comment]
有亿点麻烦
我觉得不如后者方便（

**Comment by timeForgiven** [comment]
好的，那就先用本地的吧😁谢谢大佬，说实话，能有目前的网页qq,我已经很满足了。我想要网页QQ的原因主要是我有一台windowsphone,而腾讯在2020年关闭了uwpQQ的登陆接口。只能用网页qq苟着了

**Comment by Stapxs** [comment]
UWP QQ 砍了确实傻逼（x
我之前也用来着

**Comment by timeForgiven** [comment]
> UWP QQ 砍了确实傻逼（x
> 我之前也用来着

我发了一个支付宝口令红包聊表心意，数额不大只能买买奶茶：
xxxxxxx
大佬愿意收下的话，权当是我的感谢和赞助了。未来说不定还有其他奇怪的问题需要帮忙😁

**Comment by Stapxs** [comment]
不必，大家都是因为 QQ 太难用折腾这些东西的（
能好好用着就很开心了

**Comment by timeForgiven** [comment]
> 不必，大家都是因为 QQ 太难用折腾这些东西的（ 能好好用着就很开心了

额不知道上面发的红包数字怎么突然屏蔽了😂。好的，那就这样吧。感谢帮助❤
