### ISSUE TITLE
[错误]firefox103.0.1中消息带有无意义换行

### ISSUE THREAD

**Issue by Logic-Accepted** [Stapxs/QQ-Web-Lite#33]
**描述错误**
消息会带有无规律换行

**复现流程**
使用firefox登录即可

**版本信息**
- Stapxs QQ Lite 版本：v1.2957
- 浏览器：Firefox
- 浏览器版本：103.0.1
<img width="929" alt="屏幕截图 2022-08-03 110752" src="https://user-images.githubusercontent.com/36406453/182515900-616b12ce-dd1a-47a4-b756-6b43ced5f528.png">

**Comment by Stapxs** [comment]
由 96534cfb9af1d2f81fd9f7e39ed406bee327dba0 损坏，等待修正
