### ISSUE TITLE
刷新 Web 页面后，需要进行一次鼠标左键点击后，才可进行元素选中操作

### ISSUE THREAD

**Issue by SunBK201** [Stapxs/QQ-Web-Lite#34]
**描述错误**
刷新 Web 页面后，需要进行一次鼠标左键点击后，才可进行元素选中操作

**版本信息**
我需要知道 Stapxs QQ Lite 的版本和浏览器的信息，你可以在设置的最底下看见版本信息。
- Stapxs QQ Lite 版本：v1.2957
- 浏览器：Edge & Safari

**Comment by Stapxs** [comment]
其实是已知问题 emmm 就是懒得修（
晚点再修（xxxxxx

**Comment by Stapxs** [comment]
不再打算修复此问题（1.0 已计划停止非大型错误维护）
