### ISSUE TITLE
[BUG]某群的mirai qq 转发可预览内容，但无法正常显示内容

### ISSUE THREAD

**Issue by GrassBlock1** [Stapxs/QQ-Web-Lite#37]
**描述错误**
如题，消息列表和通知都可以正常显示一部分 通过 mirai qq 实现 telegram to qq 转发 的 消息内容，但详情页无法正常显示

**复现流程**

在启用转发的群组的telegram端发送消息，qq端在同步群组正常收取，但内容显示“不支持的消息“，复制内容也正常

~~或许是故意为之罢？~~

**截图**
（如果有隐私问题请直接编辑本issue）

<img width="960" alt="捕获" src="https://user-images.githubusercontent.com/46253950/194852044-0fce164c-b5cc-44f0-8e58-92c4102c6c33.PNG">

**版本信息**
我需要知道 Stapxs QQ Lite 的版本和浏览器的信息，你可以在设置的最底下看见版本信息。
- Stapxs QQ Lite 版本：v1.2957
- 浏览器： Firefox 
- 浏览器版本： v106.0b9

**Comment by Stapxs** [comment]
暂时没有兼容 mirai qq bot 自己的协议（x

**Comment by GrassBlock1** [comment]
> 暂时没有兼容 mirai qq bot 自己的协议（虽然能接收到）

了解，期待支持。

**Comment by Stapxs** [comment]
需要补充一些信息 ——
因为找不到 mirai 自己协议的文档，如果你还能再复现出消息，我想获取一个消息示例。
- 在开发者选项中打开全部日志
![Image](https://user-images.githubusercontent.com/42486439/205577583-c750494a-a93e-4665-845c-1e8c92b3119d.png)
- 右击打卡页面的 `检查` 工具
![Image](https://user-images.githubusercontent.com/42486439/205578004-c1e68b7b-fbdb-4574-9aa5-a421052b870e.png)
- 这里面会有 GET 开头的页面获取到的消息，a像是这样
![Image](https://user-images.githubusercontent.com/42486439/205580534-a0e39d8d-d46a-40dc-adbb-3da6426ae860.png)
- 复制 mirai 发出的消息（特征应该是 messgage 下有 type 是 mirai），去掉敏感信息然后发送出来
