### ISSUE TITLE
[错误] 来自 api.stapxs.cn 的资源无法读取

### ISSUE THREAD

**Issue by wuxian425** [Stapxs/QQ-Web-Lite#43]
**描述错误**
来自 api.stapxs.cn 的资源无法读取

**复现流程**
打开站点。 

**截图**
![圖片](https://user-images.githubusercontent.com/82699919/210149443-f94ff6bf-6c84-4078-a026-4c1418f5ab19.png)

**版本信息**
我需要知道 Stapxs QQ Lite 的版本和浏览器的信息，你可以在设置的最底下看见版本信息。
- Stapxs QQ Lite 版本：最新版
- 浏览器：Firefox
- 浏览器版本：108

**Comment by wuxian425** [comment]
貌似可以了。

**Comment by Stapxs** [comment]
跨年的时候我 tomcat 服务宕机了我没注意 ……
早上改东西才发现服务炸了

**Comment by wuxian425** [comment]
啊这
