### ISSUE TITLE
查看合并消息时偶发图片渲染层次错误问题

### ISSUE THREAD

**Issue by Logic-Accepted** [Stapxs/QQ-Web-Lite#5]
重新打开合并消息也不能解决，暂未发现稳定复现的方法。图二为打开合并消息后所见。

![IMG_20220420_221925](https://user-images.githubusercontent.com/36406453/164252599-a5815172-b1ce-4dda-801e-96a924cd5775.jpg)

![IMG_20220420_221741](https://user-images.githubusercontent.com/36406453/164252854-6560c1b5-cc75-4397-bbe8-dfcd5322c146.jpg)

**Comment by Stapxs** [comment]
这个我发现了，已修待合并。

**Comment by Logic-Accepted** [comment]
好的

**Comment by Logic-Accepted** [comment]
问题仍存
![Screenshot_20220424-152235](https://user-images.githubusercontent.com/36406453/164968736-1631ec79-c0e2-4a28-a311-62666a61a490.png)
